"""Load per-product 功能说明 text and annotation blocks generated by
`ops/extract_descriptions_from_xlsx.py`.

The JSON is keyed by "{meal_type}|{name}" using half-width parens.
`get_description()` tolerates both full/half-width parens on the lookup side
and falls back to the name without a trailing parenthesized suffix.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional


_PAREN_TRANSLATION = str.maketrans({"（": "(", "）": ")"})
_TRAILING_PARENS_RE = re.compile(r"\s*\([^()]*\)\s*$")


def _normalize(name: str) -> str:
    return name.translate(_PAREN_TRANSLATION).strip()


def _strip_trailing_parens(name: str) -> str:
    return _TRAILING_PARENS_RE.sub("", name).strip()


def load_descriptions(path: Optional[Path]) -> dict:
    """Load descriptions JSON. Missing file returns an empty envelope so the
    quote pipeline keeps working without it."""
    empty = {"descriptions": {}, "annotations": {}, "package_contents": {}}
    if path is None:
        return empty
    p = Path(path)
    if not p.exists():
        return empty
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return empty
    return {
        "descriptions": dict(data.get("descriptions") or {}),
        "annotations": dict(data.get("annotations") or {}),
        "package_contents": dict(data.get("package_contents") or {}),
    }


def get_description(desc_map: Optional[dict], meal_type: str, name: str) -> str:
    """Look up a product description. Returns "" if not found or map is empty."""
    if not desc_map or not name or not meal_type:
        return ""
    descriptions = desc_map.get("descriptions") or {}
    normalized = _normalize(name)
    for candidate in (normalized, _strip_trailing_parens(normalized)):
        key = f"{meal_type}|{candidate}"
        hit = descriptions.get(key)
        if hit:
            return hit
    return ""


def get_package_contents(desc_map: Optional[dict], meal_type: str, name: str) -> list:
    """Return the sub-module breakdown for a 门店套餐, or an empty list if
    not found. Each entry: `{"商品分类", "商品名称", "单位", "功能说明"}`."""
    if not desc_map or not name or not meal_type:
        return []
    contents = desc_map.get("package_contents") or {}
    normalized = _normalize(name)
    for candidate in (normalized, _strip_trailing_parens(normalized)):
        key = f"{meal_type}|{candidate}"
        subs = contents.get(key)
        if subs:
            return [dict(s) for s in subs]
    return []


def get_annotation_block(desc_map: Optional[dict], key: str = "权益类自助充值模块") -> Optional[dict]:
    """Return `{"title": ..., "category": ..., "text_lines": [...]}` for an
    annotation block, or None if missing."""
    if not desc_map:
        return None
    annotations = desc_map.get("annotations") or {}
    block = annotations.get(key)
    if not block:
        return None
    text_lines = block.get("text_lines") or []
    if not text_lines:
        return None
    return {
        "title": key,
        "category": block.get("category", ""),
        "text_lines": list(text_lines),
    }
